@devBaseUrl = http://localhost:8787
@prodBaseUrl = https://crud-webapi-with-hono.kitamuradev.workers.dev
@basePath = api

### ==============================
### GET: /todos
### ==============================

GET {{devBaseUrl}}/{{basePath}}/todos HTTP/1.1

###

GET {{prodBaseUrl}}/{{basePath}}/todos HTTP/1.1

### ==============================
### GET: /todos/{id}
### ==============================

GET {{devBaseUrl}}/{{basePath}}/todos/1 HTTP/1.1

###

GET {{prodBaseUrl}}/{{basePath}}/todos/1 HTTP/1.1

### ==============================
### POST: /todos
### ==============================

POST {{devBaseUrl}}/{{basePath}}/todos HTTP/1.1
Content-Type: application/json

{
  "title": "new task",
  "isCompleted": 0
}

###

POST {{prodBaseUrl}}/{{basePath}}/todos HTTP/1.1
Content-Type: application/json

{
  "title": "new task",
  "isCompleted": 0
}

### ==============================
### PUT: /todos/{id}
### ==============================

PUT {{devBaseUrl}}/{{basePath}}/todos/1 HTTP/1.1
Content-Type: application/json

{
  "title": "updated task",
  "isCompleted": 1
}

###

PUT {{prodBaseUrl}}/{{basePath}}/todos/1 HTTP/1.1
Content-Type: application/json

{
  "title": "updated task",
  "isCompleted": 1
}

### ==============================
### DELETE: /todos/{id}
### ==============================

DELETE {{devBaseUrl}}/{{basePath}}/todos/1 HTTP/1.1

###

DELETE {{prodBaseUrl}}/{{basePath}}/todos/1 HTTP/1.1
